name: CI/CD Pipeline with Quality and Security Checks

on:
  push:
    branches:
      - main
      - feature/docker-setup
      - feature/k8s-deployment

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:
    # 1. Checkout source code
    - name: Checkout Source Code
      uses: actions/checkout@v3

    # 2. SonarQube (static code analysis)
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    # 3. OWASP Dependency Check (vulnerable dependencies)
    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "interior-web-app"
        format: "HTML"
        outputDirectory: reports

    # 4. Trivy (scan project files for known vulnerabilities before build)
    - name: Trivy File System Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: .

    # 5. Docker Hub Login
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 6. Build Docker Image
    - name: Build Docker Image
      run: docker build -t devopscode44/interior-web-app:latest .

    # 7. Docker Scout (inspect image for SBOM & CVEs)
    - name: Docker Scout Scan
      uses: docker/scout-action@v1
      with:
        image: devopscode44/interior-web-app:latest
        dockerhub-user: ${{ secrets.DOCKER_USERNAME }}
        dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}

    # 8. Push Docker Image
    - name: Push Docker Image
      run: docker push devopscode44/interior-web-app:latest
