name: CI/CD Pipeline with Quality and Security Checks

on:
  push:
    branches:
      - main
      - feature/docker-setup
      - feature/k8s-deployment

jobs:
  build-and-deploy:
    runs-on: [self-hosted]
    timeout-minutes: 30

    steps:
      # 1. Checkout source code
      - name: Checkout Source Code
        uses: actions/checkout@v3

      # 2. Set up JDK 17 (for rest of tools that depend on it)
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Cache SonarQube Scanner
      - name: Cache SonarQube Scanner
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      # 4. SonarQube Code Quality Scan using CLI v5+ (uses Java 17)
      - name: SonarQube Scan (Java 17 Compatible)
        uses: sonarsource/sonarqube-scan-action@v1.1.0
        with:
          cli-version: '5.0.1.3006'  # Forces newer scanner built for Java 17
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # 5. Cache OWASP Dependency Check
      - name: Cache Dependency-Check
        uses: actions/cache@v4
        with:
          path: ~/.dependency-check
          key: ${{ runner.os }}-dependency-check

      # 6. OWASP Dependency Vulnerability Check
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "interior-web-app"
          format: "HTML"
          outputDirectory: reports

      # 7. Trivy Security Scan (File System)
      - name: Trivy File System Scan
        uses: aquasecurity/trivy-action@0.11.2
        with:
          scan-type: fs
          scan-ref: .
        continue-on-error: true

      # 8. Docker Hub Login
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 9. Build Docker Image
      - name: Build Docker Image
        run: docker build -t devopscode44/interior-web-app:latest .
        timeout-minutes: 10

      # 10. Docker Scout Vulnerability Scan
      - name: Docker Scout Scan
        uses: docker/scout-action@v1
        with:
          image: devopscode44/interior-web-app:latest
          dockerhub-user: ${{ secrets.DOCKER_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
        continue-on-error: true

      # 11. Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: docker push devopscode44/interior-web-app:latest
