name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t interior-web-app:latest -f feature/docker-setup/Dockerfile .
        docker images
      shell: pwsh

    - name: Run Docker Container and Push Image
      run: |
        $container = docker run -itd -p 5000:5000 interior-web-app:latest
        Write-Output "Container ID: $container"
        docker ps
