name: CI/CD Pipeline with SonarCloud and Security Scans

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    # 1. Checkout source code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Install unzip
    - name: Install unzip
      run: sudo apt-get update && sudo apt-get install -y unzip

    # 3. Set up Java 17 (for SonarScanner and OWASP)
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 4. Cache SonarCloud packages
    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar

    # 5. SonarCloud Static Code Analysis
    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner-cli-5.0.1.3006-linux.zip
        mv sonar-scanner-5.0.1.3006-linux sonar-scanner
        export PATH=$(pwd)/sonar-scanner/bin:$PATH
        sonar-scanner \
          -Dsonar.projectKey=Prasadrasal2002_interior-web-app \
          -Dsonar.organization=prasadrasal2002 \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${SONAR_TOKEN}

    # 6. OWASP Dependency Check
    - name: OWASP Dependency Check
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
        unzip dependency-check-8.4.0-release.zip -d dc
        chmod +x dc/dependency-check/bin/dependency-check.sh
        ./dc/dependency-check/bin/dependency-check.sh \
          --project "interior-web-app" \
          --scan . \
          --format "HTML" \
          --out ./reports \
          --disableAssembly

    - name: Upload OWASP Report
      uses: actions/upload-artifact@v4
      with:
        name: owasp-report
        path: ./reports

    # 7. Trivy Vulnerability Scanner (File System Scan)
    - name: Trivy File System Scan
      uses: aquasecurity/trivy-action@0.11.2
      with:
        scan-type: fs
        scan-ref: .
      continue-on-error: true

    # 8. Docker Hub Login
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 9. Docker Build
    - name: Build Docker Image
      run: docker build -t devopscode44/interior-web-app:latest .

    # 10. Docker Scout (SBOM & CVEs)
    - name: Docker Scout Scan
      uses: docker/scout-action@v1
      with:
        image: devopscode44/interior-web-app:latest
        command: cves
        dockerhub-user: ${{ secrets.DOCKER_USERNAME }}
        dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
        summary: true
        format: json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        write-comment: true
      continue-on-error: true

    # 11. Docker Push
    - name: Push Docker Image
      run: docker push devopscode44/interior-web-app:latest

    # 12. Checkout Helm Chart
    - name: Checkout Helm Chart
      uses: actions/checkout@v3
      with:
        ref: feature/helm-chart-setup

    # 13. Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # 14. Update kubeconfig to connect to EKS
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ap-south-1 --name interior-app-eks

    # 15. Helm Deploy
    - name: Deploy to EKS using Helm
      run: |
        helm upgrade --install flask-app ./flask-app \
          --namespace default \
          --create-namespace \
          --values ./flask-app/values.yaml

    # 16. Wait for ALB DNS (Ingress)
    - name: Wait for ALB Ingress DNS
      run: |
        echo "Waiting for ALB DNS..."
        for i in {1..30}; do
          DNS=$(kubectl get ingress flask-app -n default -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
          if [[ "$DNS" != "" ]]; then
            echo "DNS=$DNS" >> $GITHUB_ENV
            echo "Found DNS: $DNS"
            break
          fi
          sleep 10
        done

    # 17. Patch DNS using .nip.io
    - name: Patch Ingress DNS
      run: |
        kubectl patch ingress flask-app -n default --type=json \
        -p='[{"op": "replace", "path": "/spec/rules/0/host", "value": "flask-app.${{ env.DNS }}.nip.io"}]'
