name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build-and-deploy:
    runs-on: [ self-hosted ]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
