name: CI/CD Pipeline with SonarCloud and Security Scans

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    # 1. Checkout source code
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}

    # 2. Install unzip
    - name: Install unzip
      run: sudo apt-get update && sudo apt-get install -y unzip

    # 3. Set up Java 17
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 4. Cache SonarCloud scanner
    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar

    # 5. Run SonarCloud Scan
    - name: Run SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner-cli-5.0.1.3006-linux.zip
        mv sonar-scanner-5.0.1.3006-linux sonar-scanner
        export PATH=$(pwd)/sonar-scanner/bin:$PATH
        sonar-scanner \
          -Dsonar.projectKey=Prasadrasal2002_interior-web-app \
          -Dsonar.organization=prasadrasal2002 \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${SONAR_TOKEN}

    # 6. Cache OWASP Dependency-Check data
    - name: Cache Dependency-Check
      uses: actions/cache@v4
      with:
        path: ~/.dependency-check
        key: ${{ runner.os }}-dependency-check

    # 7. Run OWASP Dependency-Check (without HTML to avoid crash)
    - name: OWASP Dependency Check
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
        unzip dependency-check-8.4.0-release.zip -d dc
        chmod +x dc/dependency-check/bin/dependency-check.sh
        ./dc/dependency-check/bin/dependency-check.sh \
          --project "interior-web-app" \
          --scan . \
          --format "XML" \
          --out ./reports \
          --disableAssembly

    # 8. Upload Dependency Check Report
    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: ./reports

    # 9. Trivy File System Scan
    - name: Trivy File System Scan
      uses: aquasecurity/trivy-action@0.11.2
      with:
        scan-type: fs
        scan-ref: .
      continue-on-error: true

    # 10. Checkout Dockerfile branch
    - name: Checkout Dockerfile branch
      uses: actions/checkout@v3
      with:
        ref: feature/docker-setup  # Change this if your Dockerfile is in a different branch

    # 11. Docker Hub Login
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 12. Build Docker Image
    - name: Build Docker Image
      run: docker build -t devopscode44/interior-web-app:latest .

    # 13. Docker Scout Scan (with required command input)
    - name: Docker Scout Scan
      uses: docker/scout-action@v1
      with:
        image: devopscode44/interior-web-app:latest
        command: cves
        dockerhub-user: ${{ secrets.DOCKER_USERNAME }}
        dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
        summary: true
        format: json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        write-comment: true
      continue-on-error: true

    # 14. Push Docker Image
    - name: Push Docker Image
      run: docker push devopscode44/interior-web-app:latest
