name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/docker-setup
      
jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: feature/docker-setup   # Checkout this branch explicitly

      - name: Build Docker image
        run: docker build -t interior-web-app:latest .

