name: CI/CD Pipeline

on:
  push:
    branches: [ main, feature/* ]

jobs:
  build-and-deploy:
    runs-on: [ self-hosted ]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t interior-web-app:latest .
        docker images

    - name: Run Docker Container
      id: run_container
      run: |
        CONTAINER_ID=$(docker run -itd -p 5000:5000 interior-web-app:latest)
        echo "Container ID: $CONTAINER_ID"
        echo "container_id=$CONTAINER_ID" >> $GITHUB_OUTPUT
        docker ps
